[build-system]
requires = [
    "scikit-build-core",
    "pybind11",
    "setuptools>=42",
    "scikit-build>=0.13",
    "cmake>=3.18",
    "ninja",
]
build-backend = "scikit_build_core.build"

[project]
name = "pyp"
version = "0.1.0"
description = "A Handy Python tool"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    'numpy',
    'fire',
    "imageio",
    "pillow",
]


classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering :: Physics",
]

[project.urls]
Homepage = "https://github.com/Sologala/pyp"
Documentation = "https://github.com/Sologala/pyp"
"Bug Tracker" = "https://github.com/Sologala/pyp/issues"
Discussions = "https://github.com/Sologala/pyp/discussions"



# 命令行入口 
[project.scripts]
pyp = "pyp.entry:main_entry"


